services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - mysql
      - redis
    networks:
      - laravel

      # O NOVO SERVIÇO REDIS
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
      - laravel
    volumes:
      - redis_data:/data

  # O PAINEL VISUAL
  redis-insight:
    image: 'redislabs/redisinsight:latest'
    ports:
      - '8001:8001'
    networks:
      - laravel
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

# networks:
#   laravel:

# volumes:
#   mysql_data:

# CONFIGURAÇÕES GLOBAIS (Onde o erro estava acontecendo)
networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

  